---
- name: Create the user, kube
  hosts: 'workers, masters'
  become: true

  tasks:
  - name: create a new user and name it kube
    user: name=kube append=yes state=present createhome=yes shell=/bin/bash

  - name: allow the user to run sudo without requiring a password
    lineinfile:
      path: /etc/sudoers
      line: 'kube ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

# Not working, perhaps, i need to be root.
  # - name: add authorized key for user
  #   authorized_key:
  #     user: kube
  #     state: present
  #     key: ”{{ lookup('file', '~/.ssh/citrusoft_rsa.pub') }}”
